# Generated by Django 4.2.6 on 2023-10-06 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='name',
            field=models.CharField(blank=True, default='', max_length=999, null=True),
        ),
    ]
