# Generated by Django 4.2.6 on 2024-02-19 12:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='I forgot to add title..', max_length=55)),
                ('description', models.TextField(blank=True, default='', max_length=999, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery_pics/')),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
